### ISSUE TITLE
Using the github actions yml file example in this project I get the following error...

### ISSUE THREAD

**Issue by ramsenc** [webdriverio/jasmine-boilerplate#425]
```
WARN webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
```

Followed by

```
ERROR webdriver: Request failed with status 500 due to WebDriver Error: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
[0-1]   (unknown error: DevToolsActivePort file doesn't exist)
```

Is the yml file outdated or am I missing a key component?

**Comment by christian-bromann** [comment]
> Chrome failed to start: exited abnormally.

Not sure where you run these tests but it seems that your machine has issues running Chrome.

**Comment by christian-bromann** [comment]
@ramsenc you don't need `browser-actions/setup-chrome` because GitHub already has Chrome installed in your action. To use it make sure you have `wdio-chromedriver-service` installed, then in your `wdio.conf.js`, have this:

```js
// To support testing in both GitHub Actions and locally, configure
// `wdio-chromedriver-service` based on environment variables.
// Ref: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#browsers-and-drivers
const chromedriver = !process.env.CHROMEWEBDRIVER
  ? 'chromedriver' // running locally
  : [
      'chromedriver',
      {
        chromedriverCustomPath: path.join(
          process.env.CHROMEWEBDRIVER,
          process.platform === 'win32' ? 'chromedriver.exe' : 'chromedriver'
        ),
      },
    ];

exports.config = {
  // ...
  services: [chromedriver]
  // ...
```

Check out the [`wdio-intercept-service`](https://github.com/webdriverio-community/wdio-intercept-service/tree/main/test) where this is done in the e2e test.

I will close this as it is unlikely an issue with the project, happy to support further.

**Comment by ramsenc** [comment]
Thanks for the help @christian-bromann 

I tried the code above, but I see a different error in git actions regarding the path now.

`[0-0] 2021-11-05T08:32:24.523Z ERROR webdriver: Request failed with status 400 due to Error: unhandled request
[0-0] 2021-11-05T08:32:24.523Z DEBUG webdriver: request failed due to missing body
[0-0] 2021-11-05T08:32:24.523Z ERROR webdriver: Error: unhandled request
[0-0]     at getErrorFromResponseBody (/home/runner/work/<folder>/<folder>/node_modules/webdriver/build/utils.js:191:16)
[0-0]     at NodeJSRequest._request (/home/runner/work/<folder>/<folder>/node_modules/webdriver/build/request/index.js:157:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at startWebDriverSession (/home/runner/work/<folder>/<folder>/node_modules/webdriver/build/utils.js:66:20)
[0-0]     at Function.newSession (/home/runner/work/<folder>/<folder>/node_modules/webdriver/build/index.js:58:45)
[0-0]     at remote (/home/runner/work/<folder>/<folder>/node_modules/webdriverio/build/index.js:67:22)
[0-0]     at Runner._startSession (/home/runner/work/<folder>/<folder>/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at Runner._initSession (/home/runner/work/<folder>/<folder>/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at Runner.run (/home/runner/work/<folder>/<folder>/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2021-11-05T08:32:24.525Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] The browser driver couldn't start the session. Make sure you have set the "path" correctly!
[0-0]     at startWebDriverSession (/home/runner/work/<folder>/<folder>/node_modules/webdriver/build/utils.js:71:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at Function.newSession (/home/runner/work/<folder>/<folder>/node_modules/webdriver/build/index.js:58:45)
[0-0]     at remote (/home/runner/work/<folder>/<folder>/node_modules/webdriverio/build/index.js:67:22)
[0-0]     at Runner._startSession (/home/runner/work/<folder>/<folder>/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at Runner._initSession (/home/runner/work/<folder>/<folder>/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at Runner.run (/home/runner/work/<folder>/<folder>/node_modules/@wdio/runner/build/index.js:88:19)`
